# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='col',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='player',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='row',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
