# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160701_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='col',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='move',
            name='row',
        ),
    ]
