# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160701_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
