# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160701_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
    ]
