# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160701_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
